project_id = "jjndhaxdxbbupmxiaixk"

[functions."mpesa-callback"]
verify_jwt = false

[functions.kopokopo]
verify_jwt = false

[functions.ai-chatbot]
enabled = true
verify_jwt = true
import_map = "./functions/ai-chatbot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-chatbot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-chatbot/*.html" ]
